### ISSUE TITLE
BOOTX64.EFI does not fall back to fbx64.efi / add fbx64.efi to fallback list

### ISSUE THREAD

**Issue by ConSeannery** [rhboot/shim#101]
Package: shim-x64-12-1.el7.centos.x86_64

Not sure this is the right place to bug report or if this belongs with the package maintainers - let me know.

Per https://github.com/rhboot/shim/blob/master/README.fallback
" if the boot variables are missing or corrupted,
the firmware will eventually try to boot the hard disk as removable
media.  In that case, it'll invoke \EFI\BOOT\BOOTX64.EFI (or whatever
filename is right for your architecture.)  In that case it'll be in
\EFI\BOOT, so it'll check for fallback.efi , and it'll find it and run
it."

shim-x64-12-1.el7.centos.x86_64 ships with /boot/efi/EFI/BOOT/fbx64.efi and /boot/efi/EFI/BOOT/BOOTX64.EFI

BOOTX64.EFI still tries to fall back to fallback.efi , which no longer exists, as it seems to have been renamed to fbx64.efi.

Renaming fbx64.efi to fallback.efi returns to expected behaviour (a-la previous shim rpm).

With no fallback.efi on an already installed system, we end up cycling through the fallback list and failing on the last try, ./grubx64.efi, which is not there:

fs0:\> EFI\BOOT\BOOTX64.EFI
Failed to open \EFI\BOOT\grubx64.efi - Not Found
Failed to load image \EFI\BOOT\grubx64.efi: Not Found
start_image() returned Not Found

Loading fbx64.efi directly performs expected behaviour:

fs0:\> EFI\BOOT\fbx64.efi
System BootOrder not found.  Initializing defaults.
Creating boot entry "Boot0000" with label "CentOS Linux" for file "\EFI\centos\shimx64.efi"

I do not see the string "fbx64" in this shim repo, so I assume this naming is being generated elsewhere (per-distribution rpm spec file?). If it is preferred to simply add fbx64.efi to the fallback list, let me know and i'll submit a PR.

Thanks

**Comment by jaymzh** [comment]
Talked to the amazing @vathpela who tracked this down to the old binary in shim-signed. A work around that seems safe is rebuilding the RPM with this spec change:

https://gist.github.com/jaymzh/ee1077bc91fb35f0a8be9b93603da919

**Comment by ConSeannery** [comment]
Hey @vathpela . Re: the spec change, the spec file work-around needs to be modified. This one is correct:

https://gist.github.com/ConSeannery/f84f5fba3fd532a99d70e9dc1aca13c6

Just want to make sure the working patch makes its way upstream.

Thanks
