### ISSUE TITLE
Shim-14 Enhancement Patch

### ISSUE THREAD

**Issue by TBOpen** [rhboot/shim#122]
I have attached a patch file to shim-14 which fixes a possible memory leak and fix a section for the loading of x86 kernel on UEFI64.  (I first submitted the loading x32 kernel with x64 shim years ago that peter jones implemented via ALLOW_32BIT_KERNEL_ON_X64 but a section was misunderstood and fixed in this patch).  This also adds something we need that allows us to use a common shim for multiple UEFI utilities, this is implemented as a new option where it looks for a shimx64.dat (or shimia32.dat) file that can be placed in the directory with the shim and it would contain the Unicode path (z-term) of the second stage file, otherwise falls back to the default hard-coded name.   The name in that file could be a full path if starts with \EFI\ otherwise it’s relative to where shim is.

Check it out, be nice if it was in the mainline (even if config option) in case we ever need to update the shim version in the future. 

Note something I thought of, but not going to worry about it, load_image should probably abort if the file size is zero.
[shim-14.patch.zip](https://github.com/rhboot/shim/files/1869144/shim-14.patch.zip)

**Comment by frozencemetery** [comment]
Please submit a normal pull request if you are interested in your code being included.
