### ISSUE TITLE
shim 15 bug ？

### ISSUE THREAD

**Issue by haobinnan** [rhboot/shim#123]
os: ubuntu 16.04 amd64

shim-15# make
sed	-e "s,@@VERSION@@,14," \
	-e "s,@@UNAME@@,Linux x86_64 x86_64 x86_64 GNU/Linux," \
	-e "s,@@COMMIT@@,master," \
	< /1111/shim-15/version.c.in > version.c
gcc -ggdb -O0 -fno-stack-protector -fno-strict-aliasing -fpic -fshort-wchar -Wall -Wsign-compare -Werror -fno-builtin -Werror=sign-compare -ffreestanding -std=gnu89 -I/usr/lib/gcc/x86_64-linux-gnu/5/include "-DDEFAULT_LOADER=L\"\\\\grubx64.efi\"" "-DDEFAULT_LOADER_CHAR=\"\\\\grubx64.efi\"" -nostdinc -I/1111/shim-15/Cryptlib -I/1111/shim-15/Cryptlib/Include -I/usr/include/efi -I/usr/include/efi/x86_64 -I/usr/include/efi/protocol -I/1111/shim-15/include -iquote /1111/shim-15 -iquote /1111/shim-15 -mno-mmx -mno-sse -mno-red-zone -nostdinc -maccumulate-outgoing-args -m64 -DEFI_FUNCTION_WRAPPER -DGNU_EFI_USE_MS_ABI -DNO_BUILTIN_VA_FUNCS -DMDE_CPU_X64 -DPAGE_SIZE=4096 "-DEFI_ARCH=L\"x64\"" "-DDEBUGDIR=L\"/usr/lib/debug/usr/share/shim/x64-14/\""   -c -o shim.o shim.c
shim.c: In function ‘handle_image’:
shim.c:1302:15: error: ‘gBS’ undeclared (first use in this function)
  efi_status = gBS->AllocatePages(AllocateAnyPages, EfiLoaderCode,
               ^
shim.c:1302:15: note: each undeclared identifier is reported only once for each function it appears in
shim.c: In function ‘should_use_fallback’:
shim.c:1473:15: error: ‘gBS’ undeclared (first use in this function)
  efi_status = gBS->HandleProtocol(image_handle, &EFI_LOADED_IMAGE_GUID,
               ^
shim.c: In function ‘load_image’:
shim.c:1645:15: error: ‘gBS’ undeclared (first use in this function)
  efi_status = gBS->HandleProtocol(device, &EFI_SIMPLE_FILE_SYSTEM_GUID,
               ^
shim.c: In function ‘start_image’:
shim.c:1834:15: error: ‘gBS’ undeclared (first use in this function)
  efi_status = gBS->HandleProtocol(image_handle, &EFI_LOADED_IMAGE_GUID,
               ^
shim.c: In function ‘set_second_stage’:
shim.c:2114:15: error: ‘gBS’ undeclared (first use in this function)
  efi_status = gBS->HandleProtocol(image_handle, &LoadedImageProtocol,
               ^
shim.c: In function ‘install_shim_protocols’:
shim.c:2381:15: error: ‘gBS’ undeclared (first use in this function)
  efi_status = gBS->InstallProtocolInterface(&shim_lock_handle,
               ^
shim.c: In function ‘uninstall_shim_protocols’:
shim.c:2410:2: error: ‘gBS’ undeclared (first use in this function)
  gBS->UninstallProtocolInterface(shim_lock_handle, &SHIM_LOCK_GUID,
  ^
shim.c: In function ‘efi_main’:
shim.c:2571:3: error: ‘gRT’ undeclared (first use in this function)
   gRT->ResetSystem(EfiResetShutdown, EFI_SECURITY_VIOLATION,
   ^
<builtin>: recipe for target 'shim.o' failed
make: *** [shim.o] Error 1

**Comment by lcp** [comment]
gBS and gRT are defined in efilib.h. Please check your gnu-efi headers.

**Comment by haobinnan** [comment]
It can be fixed via updating gnu-efi to 3.0.6 @lcp
