### ISSUE TITLE
Clear password

### ISSUE THREAD

**Issue by arouene** [rhboot/shim#149]
I think I forgot my password, I tried mokutil --clear-password, or mokutil --reset, each time at reboot I get a "Password doesn't match".

I there a way to reset password ?

I'm on Fedora 28 with 
  shim-x64-15-2.x86_64
  mokutil-1:0.3.0-8.fc28.x86_64

**Comment by shengis** [comment]
Strangely I do not have a MokPWStore variable in my EFI, maybe it's why I always get a "Password doesn't match" ?

**Comment by arouene** [comment]
Changed laptop / OS version ...

**Comment by nintyfan** [comment]
Same error on my PC. I try to remove this password by UEFI Shell, but it shown variable does not exist.
