### ISSUE TITLE
strlen(dppath) always return 1

### ISSUE THREAD

**Issue by YadongQi** [rhboot/shim#150]
https://github.com/rhboot/shim/blob/e563bc3dcd17d91861d3b363ed19d30228f409e1/shim.c#L2139

The strlen(dppath) always return 1. 
The dppath and PathName always starts with "\\", so the StrnCaseCmp() always returns 0 and is_our_path() always return 1.

Rootcause should be strlen uses char*, but the dppath is CHAR16 *

Replace strlen() with StrLen() could fix this issue.

**Comment by vathpela** [comment]
I'm closing this out as it was fixed in 1870bae796022f8bbf60465352eac329ff1d6ffd .  Thanks.
