### ISSUE TITLE
Reset MOK function does not cause MokListRT to be repopulated with the embedded VENDOR_CERT_FILE

### ISSUE THREAD

**Issue by cyphermox** [rhboot/shim#154]
I ran mokutil --reset with a very recent mokutil, using SHIM 15+ snapshot (3beb971b).

After rebooting and using the Reset MOK option in MokManager, the embedded certificate is no longer listed in mokutil --list-enrolled; in /proc/keys, etc.

MokListRT is empty.

**Comment by lcp** [comment]
Would you mind to try my fix?
https://github.com/lcp/shim/commit/e6ce8788f4a622da1ba5421a5eb11df163a56727

**Comment by martinezjavier** [comment]
@cyphermox I think PR #153 from @puiterwijk should fix this.

@lcp, this is very similar to your patch. Could you please review it?

**Comment by lcp** [comment]
Yeah, PR#153 should fix this bug.

**Comment by cyphermox** [comment]
Yup :)
