### ISSUE TITLE
errlog.c and mok.c are GPLv3 while everything else is BSD?

### ISSUE THREAD

**Issue by bcran** [rhboot/shim#155]
errlog.c and mok.c say they are "Distributed under terms of the GPLv3 license".
I was wondering, since the overall project (and other files, from what I can see) is BSD licensed, if that was a mistake or if they were deliberately put under the GPLv3?

**Comment by lcp** [comment]
Just checked the log. errlog.c was introduced since shim 13, so we already have the legal issue since then. This is really bad :-(

**Comment by vathpela** [comment]
Yep, I'll fix these - and I'll publicly state here that as the author of those files, you can treat them as dual-licensed with the GPLv3 text that accidentally made it in and the BSD license they should have borne.

**Comment by JohnAZoidberg** [comment]
Gentle reminder :)

**Comment by vathpela** [comment]
Done in 756384cbcfece238de3d09b149a02bf3830b551a
