### ISSUE TITLE
Bootloader has not verified loaded image error

### ISSUE THREAD

**Issue by dl200010** [rhboot/shim#172]
I am having issues with this error message. I am running Gentoo Linux and it has the Fedora M$ signed Shim in portage. I installed it and copied it to the /boot/EFI/BOOT/ and it points to grub.
I have signed both grub's efi and the kernel. I have enrolled the public cert into mok. When I boot with secure boot off no issues. When I turn it on I see grub and than it loads the kernel and it gives me the message: "Bootloader has not verified loaded image. System is compromised. Halting." I set it up so that grubx64.efi is actually my kernel and not grub. It boots just fine with secure boot off, but turn it on and I get the same message. Is there anything in the kernel config that this Shim needs to boot a kernel? I am assuming it is the kernel, since it loads Grub just fine.

**Comment by ValdikSS** [comment]
https://github.com/rhboot/shim/commit/39df41ceb5a793f7db9233a2741d30c55b6a8861

**Comment by dl200010** [comment]
Those are both patches for Grub2. I even tried to launch the kernel directly, using efi stub set up inside the kernel, and no grub I get the same error. Is there something like those grub patches for the kernel?

**Comment by ValdikSS** [comment]
As far as I understand (I'm neither shim developer nor UEFI expert), shim is designed to be used for a "participating bootloader". That means that the bootloader should either use standard UEFI image loading functions LoadImage()/StartImage() or, if the bootloader loads payload by itself, use shim_lock protocol for file verification.

Default GRUB2 (from gnu.org, without Secure Boot patches) `linux` command loads Linux kernel with internal loader, and does not support shim_lock protocol. As soon as Linux is loaded, GRUB calls `ExitBootServices()` command, which is hooked by shim. Calling `ExitBootServices()` without shim_lock->verify or LoadImage/StartImage is considered as non-participating bootloader, and shim shows the message and shuts down the PC.
EFISTUB-loaded kernel also does exactly that, that's why you get this message.

You need one of:
* participating bootloader which support shim_lock protocol (GRUB2 with Secure Boot patches: https://github.com/rhboot/grub2/tree/fedora-30)
* participating bootloader which loads Linux using `linuxefi` (not sure if it's supported on stock GRUB2)
* bootloader which uses LoadImage/StartImage to load EFISTUB (try `chainloader /path/to/kernel.efi`, but you can't load initrd this way, you'll need to set initrd path as the kernel command line argument)
* hacked bootloader which calls shim_lock->verify once for a random data (so shim treats it as participating bootloader) and does anything it should afterwards.

Why do you need shim for your setup anyway?

**Comment by dl200010** [comment]
I want to have my secure boot turned on because I am dual booting windows as well. My laptop bios lacks the key management for secure boot keys, otherwise I would just have gone the route of putting keys in the bios. I can only turn it on and off, but I cannot clear the keys out to put new ones in. There is a way around it, but it is dangerous and I would risk bricking my laptop (link below). It is also not for the same model I have. 

https://lukegb.com/posts/2016-11-11-secure-boot-shenanigans/

I am going to build the GRUB2 fedora 30, and give that a shot.

**Comment by dl200010** [comment]
Well, sadly I cannot get grub2 from Fedora 30 to build. Complains about missing files.

**Comment by ValdikSS** [comment]
>I want to have my secure boot turned on because I am dual booting windows as well.

Does Windows behave differently with Secure Boot off or on? Why do you want to keep it on?

>Well, sadly I cannot get grub2 from Fedora 30 to build. Complains about missing files.

Try `master-sb` or `fedora-29` branch.

**Comment by martinezjavier** [comment]
> Well, sadly I cannot get grub2 from Fedora 30 to build. Complains about missing files.

What error exactly are you getting when building the `fedora-30` branch?

**Comment by dl200010** [comment]
I want secure boot not because windows changes without it, but because it is an anti malware mechanism and windows has malware issues. Trying to get it turned on in Linux, because it is annoying to turn off for Linux and back on for windows.

When trying to build I ran the first two sh scripts in the install file. It didn't create the configure script. I ran autoconf, and it created the script. Running the configure script complains about "install-sh or install.sh" not being in "build-aux."

**Comment by dl200010** [comment]
Where is the patch that brings the SB changes? I know I can get Gentoo's emerge to apply patches while installing.

**Comment by ValdikSS** [comment]
Secure Boot protects only from bootkits and bootloader modification. It does not add additional security against overwhelming majority of common Windows malware which does not interact with booting process.
You can get Secure Boot support patchset as patch files from Ubuntu or Fedora package.

**Comment by dl200010** [comment]
That is exactly why I want it. I have had malware replace my bootloader before and I want to avoid it happening again. That is why I was happy that secure boot came along.

**Comment by ValdikSS** [comment]
Why would you want to use shim then? You can generate your own key, sign the kernel an grub with it, add it into UEFI db with keytool.

**Comment by dl200010** [comment]
My laptop bios lacks the key management for secure boot keys, otherwise I would just have gone the route of putting keys in the bios. I can only turn it on and off, but I cannot clear the keys out to put new ones in. There is a way around it, but it is dangerous and I would risk bricking my laptop (link below). It is also not for the same model I have.

https://lukegb.com/posts/2016-11-11-secure-boot-shenanigans/

KeyTool cannot clear the keys, even Rod Smith says that.

**Comment by dl200010** [comment]
I even have a support ticket open with Razer to get at least the key management unlocked and accessible, but they are being resistant AND even lied to me saying that installing Linux would void the warranty, the GPU only works with Windows, the Synapse only works on windows, and "embedded software" might be corrupted.

**Comment by dl200010** [comment]
I found two patches from openSUSE. Are these the secure boot patches I would need?
https://build.opensuse.org/package/view_file/openSUSE:Factory/grub2/grub2-secureboot-chainloader.patch
https://build.opensuse.org/package/view_file/openSUSE:Factory/grub2/grub2-secureboot-add-linuxefi.patch

**Comment by dl200010** [comment]
I patched the grub with those two patches, and now it won't boot an unsigned kernel but boots a signed one just fine. Secure Boot on! FYI: even the chain loader in stock grub requires a secure boot patch.

When booting grub spits out "EFI stub: UEFI Secure Boot is enabled.", but dmesg still says "Secure boot could not be determined." Don't know if that is really an issue.

Thanks so much guys!!!!!!

**Comment by codernavi18** [comment]
> > Well, sadly I cannot get grub2 from Fedora 30 to build. Complains about missing files.
> 
> What error exactly are you getting when building the `fedora-30` branch?

After we run "autogen.sh", there is no "configure" script generated.

**Comment by codernavi18** [comment]
> I found two patches from openSUSE. Are these the secure boot patches I would need?
> https://build.opensuse.org/package/view_file/openSUSE:Factory/grub2/grub2-secureboot-chainloader.patch
> https://build.opensuse.org/package/view_file/openSUSE:Factory/grub2/grub2-secureboot-add-linuxefi.patch

The second patch looks incomplete to me. It does not even verify the loaded kernel. In fact comparing the same patch to Matthew Garrett's patch [(here),](https://github.com/coreos/grub/commit/23589dc78b3e35eaba8b2a12df03d018184a0a19) the call to `grub_linuxefi_secure_validate( )` is missing when the kernel image is read in `grub_cmd_linux()`
