### ISSUE TITLE
MokManager screen not being drawn properly

### ISSUE THREAD

**Issue by Randune** [rhboot/shim#177]
When running mmx64.efi from the EFI shell, the introductory screen for MokManager doesn't draw entirely, the only thing drawn on the screen is the text which says "Press any key to perform Mok Management" and the countdown timer, the rest of the screen is not drawn (I can see the EFI shell in behind) and when I press any key to continue, the counter stops but the next screen isn't drawn, I know the program is running because when I press Esc it quits back to the EFI shell.  *See the attachment*
![mok_manager](https://user-images.githubusercontent.com/50386677/57341386-3e469180-7108-11e9-9fbe-77223bed6822.jpg)

**Comment by gibmat** [comment]
I have run into this same issue as well while trying to boot into MokManager under a Debian 10 (buster) install; shim-unsigned package version is 15+1533136590.3beb971-7.

There are a few other reports of similar issues online:
* https://askubuntu.com/questions/950395/mok-management-will-not-load-on-boot
* https://bugzilla.redhat.com/show_bug.cgi?id=1520709

The common thread seems to be encountering this issue on ASRock motherboards. The machine I've been working on has a Z270M Pro4 motherboard.

I'd be happy to help test/debug potential solutions to this issue, although I don't have the necessary insight to suggest potential fixes.

**Comment by Randune** [comment]
I opened a ticket with ASRock about this issue, I told them that it is a common problem among ASRock motherboards, and they simply said "we don't support any linux version".

I proceeded to tell them that this isn't a linux issue, as MokManager is an EFI application, not a linux application, but I never received a response after that.  I wish we could get some weight behind this issue and pressure them to do something about it.

**Comment by gibmat** [comment]
Yup, it's disappointing when manufacturers believe Windows is the only thing to ever run on their hardware.

**Comment by Randune** [comment]
ok, I've opened another ticket with ASRock, hopefully we can gain some traction regarding this issue.

**Comment by jeremyvisser** [comment]
I have an ASRock X470 Taichi which also suffers from this exact issue.

**Comment by tommyvct** [comment]
Still nothing?

**Comment by jjohnson42** [comment]
> I got an ASRock X399 Taichi and have encountered the same problem. This MB allows you to clear the keys and installing default keys from the setup, but not importing custom keys. I tried contacting ASRock support but all I got in reply was “_… supports Secure Boot for Win 10 OS only_”.
> 
> Since parts of the application renders I decided to poke around a bit. It turns out that the problem is related to the `console_print_box_at()` function in `console.c`. If you replace the `BOXDRAW_*` special characters with normal ASCII characters (I used `|+-`) the applications renders correctly.
> 
> As a side note, looks like the `console.c` file originate from the `efitools` project. The exactly same problem affects `efitools` and it can be solved in the same way. Just replace the special characters. However, it turns out there are more problems in the ASRock firmware, because when I used `efitools` to replace the `db`, `KEK` and `PK` keys I had to re-flash my UEFI to even be able to even enter setup again.
> 
> This is the last time I buy ASRock.

Could a pull request for this change be considered?

**Comment by gibmat** [comment]
I'd be happy to test changes if it's possible to get a build from a PR to this repo. I'll echo the others, though -- no more ASRock for me!

**Comment by Arnavion** [comment]
If I understand correctly, #271 was unmerged (force-pushed out of history?), and https://github.com/rhboot/shim/pull/428 is the replacement which has not yet been released in any version of shim. Perhaps this issue could be re-opened to reduce confusion for users like me.
