### ISSUE TITLE
Passing arguments always output dppath and path variables

### ISSUE THREAD

**Issue by howl** [rhboot/shim#179]
I started to use the shim's ability to get the second loader filename but I encountered that always output the content of two variables: dppath a path.

I think is something left at debug because is inside the is_our_path procedure used to avoid issues in some firmwares that sends the shim's own path as a parameter.

https://github.com/rhboot/shim/blob/a4a1fbe728c9545fc5647129df0cf1593b953bec/shim.c#L2149-L2150

If I'm not in a mistake that output should be removed.

**Comment by howl** [comment]
I have made a pull request for this https://github.com/rhboot/shim/pull/180

**Comment by vathpela** [comment]
I believe there's no remaining issue here, so I'm closing this.  If I'm wrong,  please reopen.
