### ISSUE TITLE
Bad CompareGuid comparison in tpm_data_measured

### ISSUE THREAD

**Issue by mdempsky** [rhboot/shim#185]
I believe the call to CompareGuid here:

https://github.com/rhboot/shim/blob/a4a1fbe728c9545fc5647129df0cf1593b953bec/tpm.c#L241-L244

should actually include a `== 0` comparison, like how CompareGuid is used throughout the rest of shim. The effect of this is that tpm_measure_variable may measure redundant events, because it will erroneously think the GUID always differs.

I suspect this is related to why the event log on my X1 Carbon only lists the "Shim" event once, yet I need to replay the event twice to reconstruct the final PCR value reported by my TPM: https://lists.01.org/pipermail/tpm2/2019-September/001363.html

(I'm guessing the BIOS's hash_log_extend_event function always hashes the PCR value, but only extends the log when it's unique. Or that the Linux kernel is deduplicating log entries before providing it to userland as binary_bios_measurements.)

**Comment by cyphermox** [comment]
Yup, Chris's PR at https://github.com/rhboot/shim/pull/187 addresses this.
