### ISSUE TITLE
Custom loader on external device

### ISSUE THREAD

**Issue by pinembour** [rhboot/shim#186]
Can shim load a custom loader that's on an external device ?
I saw that I can modify the build options, but I'm a bit lost on how I should tell it to look in, for example, /dev/sdb1 for a file called linuz.efi, with the leading backslashes and everything.

**Comment by vathpela** [comment]
It can, though it doesn't have any concept of /dev/sdb1.  In general it tries to load the second stage from a path relative to the location shim was loaded from, which is what DEFAULT_LOADER describes, unless it gets load options (i.e. command line options), in which case it will try to load from the path specified on the command line.
