### ISSUE TITLE
regression (3beb971 -> a4a1fbe): fails to load fwupd

### ISSUE THREAD

**Issue by julian-klode** [rhboot/shim#194]
In Ubuntu, we recently updated our shim snapshot from 3beb971 to a4a1fbe - and we realized a bit after that that we cannot load fwupd anymore.

fwupdx64.efi is located in `\EFI\ubuntu\` alongside `shimx64.efi`, it's bootloader entry is

```
Boot0001* Linux-Firmware-Updater        HD(1,GPT,a155bb6c-2d31-4a90-8678-f0f921e11e9b,0x800,0x100000)/File(\EFI\ubuntu\shimx64.efi)\.f.w.u.p.d.x.6.4...e.f.i...
```
This worked fine in commit 3beb971, but fails to load in commit a4a1fbe - shim just loads grub instead.

I tried launching `fwupdx64.efi` from an EFI shell as well, but `shimx64.efi fwupdx64.efi` also loaded grub (though that might be caused by #181).

I tried copying `fwupdx64.efi` to the root of the ESP, because there was a slash in front of it, but that did not seem to help either.

My next step would be to bisect this, but I'm going to need time to set this up first (wanna bisect in a VM, not on my actual machine), so I'm writing the bug first.

**Comment by superm1** [comment]
Before bothering to bisect, maybe try updating to a _newer_ snapshot of shim?

**Comment by superm1** [comment]
That being said, https://github.com/rhboot/shim/commit/a625fa5096ccdf87036379a5cb237bd43516d605 and https://github.com/rhboot/shim/commit/e563bc3dcd17d91861d3b363ed19d30228f409e1 would be the most suspicious commits to me which haven't changed in any significant way in master.

**Comment by martinezjavier** [comment]
@julian-klode as @superm1 correctly pointed out, commit e563bc3 is the one to blame for this bug. 

In the `is_our_path()` function, two UCS-2 strings are compared but I wrongly used `strlen()` to calculate the string length instead of using `StrLen()`. Sorry about that...

@vathpela  fixed this bug some time ago with commit 1870bae ("Fix a use of strlen() instead of Strlen()").

**Comment by superm1** [comment]
@martinezjavier thanks for your confirmation and pointer on the fixed commit.  I suppose this can be closed now then.

**Comment by martinezjavier** [comment]
@superm1 you are welcome. Yes, I'll close it now. Sorry for the inconvenience with this bug.

**Comment by julian-klode** [comment]
Uh, um, this should have gone to the invalid fwupd bug I suppose, as I need to see if I can load fwupd from shim and hence need fwupd to install itself to the ESP and the boot order, which it does not do if there are no update-able devices.

**Comment by superm1** [comment]
@julian-klode Assuming you have an updatable device, you should be able to use the `reinstall` command in fwupd to try to reinstall the current firmware.

**Comment by julian-klode** [comment]
Oh I was dumb, and never actually updated the shim on the ESP, hence why it still failed, sorry for the noise. Time to finish the update and start signing request and stuff.
