### ISSUE TITLE
Fedora is disabling openSUSE's MOK validation

### ISSUE THREAD

**Issue by surprized** [rhboot/shim#219]
I am not sure if this should be happening, but it seems like a security flaw to me (I'm no expert, though).

So I ran "mokutil --disable-validation" in order to get NVIDIA drivers working along secure boot by the 'easy way', on Fedora. After a reboot, I typed the password in and disabled validation; then, I loaded openSUSE and I got the insecure boot warning from shim/grub, implying it got disabled for it as well. Fedora and openSUSE are using separate EFI partitions.

Just to make sure that no bootloader files from openSUSE were being modified (which would be weird), I disabled my drive containing openSUSE after running mokutil --enable-validation, and then disabled validation from Fedora again. After completing the process, I enabled the drive with opensSUSE and the validation was disabled there as well.

Since the external OS is the one choosing the password, if any other OS got compromised and the drive wasn't encrypted, it would make it easier to compromise those as well. Consider that relatively few people encrypt their drives and a lot of them dual boot.

My guess is that Fedora and openSUSE are sharing TPM memory; could it be possible to separate their data or is it an UEFI limitation?

I tried finding any reports or documentation about this behavior, but I couldn't. If there is any, let me know please.

**Comment by vathpela** [comment]
This isn't Operating System state, this is machine state; all the operating systems set the machine state in the same set of UEFI variables.  This is the expected behavior, though you're right that it's under-documented.
