### ISSUE TITLE
latest tags (15.1, 15.2) are no longer signed

### ISSUE THREAD

**Issue by dvzrv** [rhboot/shim#304]
Hi! I package shim for Arch Linux. Currently I am not able to upgrade the package.

To verify the authenticity of the upstream releases we often rely on the cryptographic signatures offered by upstream developers.
For tags between 11 and 15 the tags have been signed with the key of @vathpela (before that only sporadically). However, the two releases 15.1 and 15.2 are not signed any longer.

Given the nature of this software and the great potential for a [supply chain attack](https://en.wikipedia.org/wiki/Supply_chain_attack), I would like to ask you to please continue signing the release tags and establish a [chain of trust](https://en.wikipedia.org/wiki/Chain_of_trust) to any other collaborator's key, that is allowed to (also or in the future) create a release tag. This would improve the verification possibilities of downstreams a great deal.

**Comment by xnox** [comment]
Is this resolved for you now? 15.3 & 15.4 look like GPG signed tags to me.

**Comment by dvzrv** [comment]
@xnox yes, the tags are signed again.

@vathpela It would be awesome if you could specify the expected PGP key ID used for signatures on tags/releases in a document (e.g. README.md) using a signed commit. Extending such a document later is the easiest way of providing a chain of trust going onward in case someone else will become (additional) release manager in the future.

Other than that, the issue with the tags is fixed, so I will close this ticket.
