### ISSUE TITLE
.gitmodules for shim-15.4 still points to gnu-efi:shim-15.3

### ISSUE THREAD

**Issue by realnickel** [rhboot/shim#356]
https://github.com/rhboot/shim/blob/shim-15.4/.gitmodules

[submodule "gnu-efi"]
	path = gnu-efi
	url = https://github.com/rhboot/gnu-efi.git
	branch = shim-15.3

**Comment by xnox** [comment]
Whilst true, the actual commit that gnu-efi is pinned to is the right one.

```
$ git ls-tree HEAD | grep gnu-efi
160000 commit f0f98248649b4b219764bd46854697bcec858081	gnu-efi
```

aka the 15.4 branch, and that's the same gnu-efi commit that is vendored in the 15.4 bz2 tarball in the release files.

**Comment by xnox** [comment]
@vathpela maybe worth pushing correct branch names to all the branches that have .gitmodules?
