### ISSUE TITLE
The "Error: Locate graphic output protocol fail: (0xE) Not Found." always be showed if platform doesn't provide EFI_GRAPHICS_OUTPUT_PROTOCOL

### ISSUE THREAD

**Issue by joeyli** [rhboot/shim#440]
On some platform, like GCP or OVMF which does NOT provide EFI_GRAPHICS_OUTPUT_PROTOCOL when no display device (or display device be disabled). It causes that the "Error: Locate graphic output protocol fail: (0xE) Not Found." always be showed on console when we enroll MOK through MokManager.

**Comment by joeyli** [comment]
I have sent a pull request here: https://github.com/rhboot/shim/pull/441

The patch removed the "Error: Locate graphic output protocol fail: (0xE) Not Found." message box.

**Comment by dennis-tseng99** [comment]
If gop(Graphic Output Protocol) is not implemented in your platform, then a small window box will prompt and be waiting for a keystroke pressed by user, such that no more action can be implicitly continued thereafter. For example, VM cannot be accessed . There are 2 solutions:
[sol-1]
Following Joey's suggestion, we can just remove the warning window box generated by console_error() function.
efi_status = gBS->LocateProtocol(&gop_guid, NULL, (void **)&gop);
if (EFI_ERROR(efi_status)) {
    **console_error(L"Locate graphic output protocol fail", efi_status);**
    return;
}
[sol-2]
Let timer to control warning window box generated by console_countdown() function.
efi_status = gBS->LocateProtocol(&gop_guid, NULL, (void **)&gop);
if (EFI_ERROR(efi_status)) {
    **console_countdown(title,L"cannot find a graphic output protocol",timeout);**
    return;
}
Any comments are welcome :-)

**Comment by joeyli** [comment]
Close this issue because patch be merged to shim mainline.
