### ISSUE TITLE
15.7 is not signed

### ISSUE THREAD

**Issue by dvzrv** [rhboot/shim#529]
Hi! I package shim for Arch Linux.
To ensure the chain of trust between releases, I check the signatures made for the respective tags. @vathpela it seems you forgot to sign 15.7.

Please make sure to continue signing the releases (also see https://github.com/rhboot/shim/issues/304), as shim is central to the secure boot setup on many downstream distributions.

**Comment by frozencemetery** [comment]
Fixed

**Comment by julian-klode** [comment]
Tarballs probably should have detached signatures, but at least you can now reproduce them with `make test-archive` :)
