### ISSUE TITLE
shim image loader assumes padding relocs are added by GenFw, but not all efi files have this

### ISSUE THREAD

**Issue by mikebeaton** [rhboot/shim#561]
The shim handle_image method assumes that RelocDir->Size == Section->Misc.VirtualSize, but in fact this is not required.

While current EDK-II GenFw generates files where the above-mentioned two values are equal (and also pads the .reloc section above RelocDir->Size with dummy reloc entries, which the shim loader processes), in general RelocDir->Size may be smaller than the padding aligned Section->Misc.VirtualSize of the .reloc section, and the padding area need not contain dummy reloc entries.

When an .efi file loaded by shim does not match this current requirement, the file loads but then crashes with a page fault because the relocations have been silently dropped by shim. However the same .efi file(s) [see message below] start fine on the firmware of multiple systems, including OVMF - and on shim when modified by the linked PR.

Attached is a version of UEFI Shell showing this issue. It is loaded fine by the firmware of many systems, and we believe is fully valid, but is not currently loaded successfully by the shim image handler, instead showing this issue.

[OpenShell.zip](https://github.com/rhboot/shim/files/11188602/OpenShell.zip)

**Comment by mikebeaton** [comment]
Related: https://github.com/acidanthera/bugtracker/issues/2239
Possibly related(?): https://github.com/rhboot/shim/issues/97

**Comment by vit9696** [comment]
@vathpela, any progress on this? The issue is currently a blocker for us. Thanks!

**Comment by mikebeaton** [comment]
Closed with https://github.com/rhboot/shim/pull/562#issuecomment-1601343882 - tyvm
