### ISSUE TITLE
Can shim load UKI efi images from /boot

### ISSUE THREAD

**Issue by flixman** [rhboot/shim#571]
This is not an issue but a question: my EFI (/efi) partition is small and I am currently booting through systemd-boot kernels located in /boot. I am looking forward to switching to shim + UKI and I was wondering: can shim boot UKI images stored in /boot? If so I could take out systemd-boot.

**Comment by julian-klode** [comment]
If your UKIs are signed correctly, and you add boot entries to the UEFI boot menu for them like https://github.com/canonical/nullboot does (which is highly specialized) - syntax being `shimx64.efi <path to UKI> <kernel options>` then sure.

Obviously it's not a boot manager, it doesn't have a menu or find your UKIs for you. Unless you only want one and call it grubx64.efi :D
