### ISSUE TITLE
Building shim with more than one certificate

### ISSUE THREAD

**Issue by crempel-redhat** [rhboot/shim#603]
I'm trying to understand if this is even possible.  Looking at shim.c it would appear that only a single certificate (i.e. make VENDOR_CERT_FILE=pub.cer) can be embedded, however, the shim-review repo README.md implies that more than one certificate can be used: _"add any additional binaries/certificates/SHA256 hashes that may be needed"_

What I would like to be able to do is keep the existing Fedora certificate for validating kernel and modules but also have my own embedded certificate to validate a customized GRUB image as opposed to adding it to db (i.e. wide distribution, not just my system).  

Or perhaps I'm interpreting the README.md wording incorrectly.   If shim cannot accommodate more than one certificate, I guess the alternative is to build with my certificate and then sign everything?

**Comment by aronowski** [comment]
> If shim cannot accommodate more than one certificate, I guess the alternative is to build with my certificate and then sign everything?

Why not enroll a CA certificate to MokList instead?

I've described the process in the context of AlmaLinux ELevate [here](https://github.com/AlmaLinux/wiki/pull/287/files). Try it, see if it does the job well for you.

**Comment by crempel-redhat** [comment]
Thanks, and sorry, I neglected to mention that my use case does not permit modification of the MOK list.  But otherwise, yes, that would work.

**Comment by mikebeaton** [comment]
I believe you would need VENDOR_DB_FILE instead of VENDOR_CERT_FILE (can only use one or the other, not both).

**Comment by mikebeaton** [comment]
Can close this issue I guess? (Maybe with separate one requesting more documentation...?? ;-) )

**Comment by crempel-redhat** [comment]
Apologies for the delay, yes, I'll close it :-)
