### ISSUE TITLE
A request for low-level developers

### ISSUE THREAD

**Issue by Jurij-Ivastsuk** [rhboot/shim#635]
@julian-klode , @jsetje , @vathpela , @lcp , @martinezjavier , @chrisccoulson , @jprvita , @vorlonofportland

Hello everyone, I don't know who to speak to personally about this matter. That's why I'm trying to contact all the developers who have contributed to Shim's development. Mr. Kamil Aronowski (@aronowski) suggested me to contact someone from low-level development to have our pool request ([pull/626](https://github.com/rhboot/shim/pull/626))) evaluated. Without this change I suggested [(pull/626)](https://github.com/rhboot/shim/pull/626) we cannot use Shim error-free. And on top of that, we need the Shim review [(362)](https://github.com/rhboot/shim-review/issues/362) for a bug-free version of Shim. I ask you, if someone has time, to have a look at this pool request and if everything is OK from your point of view, to accept this PR.

**Comment by jprvita** [comment]
I am not too involved with shim these days, but since I had a few minutes to spare, I left a couple of generic comments on your PR.

**Comment by Jurij-Ivastsuk** [comment]
Thank you
