### ISSUE TITLE
Issues with GRUB 2.12 Loading Signed Linux Kernel

### ISSUE THREAD

**Issue by haobinnan** [rhboot/shim#684]
I previously used GRUB 2.06 and now need to upgrade to 2.12. However, during the Linux kernel loading stage, I receive this message. Could you please explain what might be causing this issue? The Linux kernel has also been signed.

**Comment by haobinnan** [comment]
![屏幕截图 2024-08-19 134919](https://github.com/user-attachments/assets/968794a9-40f1-42e7-9df7-eafe7032f624)

**Comment by haobinnan** [comment]
![屏幕截图 2024-08-19 134935](https://github.com/user-attachments/assets/59422de9-0e92-4d2f-8e98-01c65ed25a1e)

**Comment by haobinnan** [comment]
@steve-mcintyre 

Thank you very much; I hope you can guide me on this. The same kernel works fine with GRUB 2.06 without any error messages, but after upgrading to 2.12, the error appears. Below is the code address: https://git.launchpad.net/ubuntu/+source/grub2/tag/?h=import/2.12-5ubuntu4

**Comment by haobinnan** [comment]
grub2 menu.cfg

insmod part_gpt
insmod part_msdos
insmod png
insmod all_video
insmod gfxterm

loadfont $prefix/font.pf2

set timeout=0
set default=0
set gfxpayload=1024x768

menuentry 'EassosRestore' {
    if cpuid -l; then
        echo 'Loading ...'
        linux /EassosRestoreBoot/bzImage loglevel=3
        initrd /EassosRestoreBoot/initramfs
    else
        echo 'This CPU is not compatible with 64-bit mode.'
        sleep 3
        reboot
    fi
}

**Comment by haobinnan** [comment]
When using GRUB 2.12, do you need to apply any additional patches to the Linux kernel?

**Comment by kukrimate** [comment]
Are you building the peimage module into your GRUB?

Also you need to have EFI stub enabled in your kernel Kconfig to boot.

**Comment by haobinnan** [comment]
Thank you very much! The issue was that my GRUB2 didn't include the peimage module. After including peimage, it booted normally.
@kukrimate
