### ISSUE TITLE
Dell boards, arguments are not actually passed to the EFI executable

### ISSUE THREAD

**Issue by alexojegu** [rhboot/shim#698]
It seems that Dell boards have an issue where arguments are not passed to the EFI executable, here is the Linux EFI thread about it:
https://lore.kernel.org/linux-efi/20200907170021.GA2284449@rani.riverdale.lan/

Would it be possible to implement a workaround? My goal is to be able to load `systemd-bootx64.efi` instead of `grubx64.efi` (Shim is supposed to load the EFI file given to it as an argument before loading the hardcoded `grubx64.efi`, if I'm not mistaken)
```
efibootmgr --disk /dev/sda --part 1 --create --label "Linux Boot Manager" --loader '\EFI\Systemd\shimx64.efi' --unicode '\EFI\Systemd\systemd-bootx64.efi'
```

I guess something similar to the workaround implemented in Linux 5.10 should work:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4a568ce29d3f48df95919f82a80e4b9be7ea0dc1

**Comment by polarina** [comment]
Have you tried null terminating the argument string? I've encountered firmware who read memory out-of-bounds otherwise.
```sh
printf '%s\0' "\EFI\Systemd\systemd-bootx64.efi" | sed 's/./&\x00/g' | \
	efibootmgr --create -d /dev/sda -p 1 \
		-L 'Linux Boot Manager' \
		-l '\EFI\Systemd\shimx64.efi' \
		-@ -
```

**Comment by alexojegu** [comment]
Thank you very much @polarina, it's working!!!
