### ISSUE TITLE
Allow for enrollment of hash with hash only (without file)

### ISSUE THREAD

**Issue by StevenDoesStuffs** [rhboot/shim#72]
For users with an encrypted boot partition, keeping an updated version the kernel in a fat fs may be problematic. It would be easier to just keep the hash instead of the kernel in a fs where MokManager could access it instead. Is it possible to enroll a hash without the file?

**Comment by lcp** [comment]
# mokutil --import-hash <your hash>

**Comment by StevenTheEVILZ** [comment]
Ah, but that requires the computer to be booted. I'm sorry, I know this is a very peculiar request, but I need to be able to do it from MokManager, because in my situation, I may not be able to boot the computer.

**Comment by lcp** [comment]
That sounds strange to me. For SUSE/openSUSE, we also put grub.efi in ESP and keep the kernel in the encrypted partition. Wonder why your signature couldn't be verified.

**Comment by StevenTheEVILZ** [comment]
@lcp Do you have any tips on how to solve this proiblem or a solution?

**Comment by lcp** [comment]
Could you reproduce the issue with OVMF? It's easier to debug shim in a virtual machine. At least you can attach gdb to shim to get more information.
