### ISSUE TITLE
What happens if LoadOption is L"\0" ?

### ISSUE THREAD

**Issue by edjee** [rhboot/shim#95]
https://github.com/rhboot/shim/blob/e06765ae0dbbc874ff9e04dbd0e7d82989048261/shim.c#L2531

Hi @vathpela , may I ask about the function "set_second_stage" in shim.c ?

If the LoadOption data happens to be L"\0" , what's the expected results?
I found that the function "count_ucs2_strings" returns 1, when the input is L"\0".

In such a case, do we want to fall back to DEFAULT_LOADER? Or halt?

**Comment by edjee** [comment]
To me it's strange that count_ucs2_strings() returns 1 for the input L"\0".
Is that an expected behavior? Shouldn't it return 0?

**Comment by vathpela** [comment]
L"\0" is one string of length 0.  That looks right to me.
I think we want DEFAULT_LOADER in this case.
